//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionTokenScopes sessionTokenContextKey = "sessionToken.Scopes"
)

// Defines values for AuthSessionTokenType.
const (
	Bearer AuthSessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthSessionTokenType enum.
func (e AuthSessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Account An application-domain account (`accounts` table). `isAdmin` mirrors the server-level `is_admin` flag; it never carries per-game roles, which are surfaced by `GET /me/games`.
type Account struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DisplayName How the person wants to be addressed; may be empty.
	DisplayName *string             `json:"displayName,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Id          int64               `json:"id"`

	// IsActive The negation of the stored `inactive` flag.
	IsActive bool `json:"isActive"`

	// IsAdmin Server-level administrator (`accounts.is_admin`).
	IsAdmin   bool       `json:"isAdmin"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	// Account An application-domain account (`accounts` table). `isAdmin` mirrors the server-level `is_admin` flag; it never carries per-game roles, which are surfaced by `GET /me/games`.
	Account Account `json:"account"`
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	// ExpiresAt When the session expires.
	ExpiresAt time.Time `json:"expiresAt"`

	// Token Opaque session token; present as a bearer credential. Shown once.
	Token     string               `json:"token"`
	TokenType AuthSessionTokenType `json:"tokenType"`
}

// AuthSessionTokenType defines model for AuthSession.TokenType.
type AuthSessionTokenType string

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	// CurrentSecret The caller's current secret, verified before the change.
	CurrentSecret string `json:"currentSecret"`

	// NewEmail New email; lowercased and must be unique.
	NewEmail openapi_types.Email `json:"newEmail"`
}

// ChangeSecretRequest defines model for ChangeSecretRequest.
type ChangeSecretRequest struct {
	// CurrentSecret The account's existing secret, verified before the change.
	CurrentSecret string `json:"currentSecret"`

	// NewSecret The replacement secret (at least 8 characters).
	NewSecret string `json:"newSecret"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	DisplayName *string `json:"displayName,omitempty"`

	// Email Lowercased and must be unique.
	Email    openapi_types.Email `json:"email"`
	IsActive *bool               `json:"isActive,omitempty"`
	IsAdmin  *bool               `json:"isAdmin,omitempty"`

	// Secret Optional; if omitted a random one is generated and returned once.
	Secret *string `json:"secret,omitempty"`
}

// CreateAccountResponse defines model for CreateAccountResponse.
type CreateAccountResponse struct {
	// Account An application-domain account (`accounts` table). `isAdmin` mirrors the server-level `is_admin` flag; it never carries per-game roles, which are surfaced by `GET /me/games`.
	Account Account `json:"account"`

	// GeneratedSecret The plaintext secret, present only when one was generated. Shown once; only its bcrypt hash is stored.
	GeneratedSecret *string `json:"generatedSecret,omitempty"`
}

// DatabaseVersion defines model for DatabaseVersion.
type DatabaseVersion struct {
	// SchemaVersion Migrations applied to the open database (SQLite user_version).
	SchemaVersion int32 `json:"schemaVersion"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Stable, machine-readable error code.
		Code string `json:"code"`

		// Message Human-readable explanation.
		Message string `json:"message"`

		// RequestId Correlation id for the request, for support and log tracing.
		RequestId *string `json:"requestId,omitempty"`
	} `json:"error"`
}

// ListAccountsResponse defines model for ListAccountsResponse.
type ListAccountsResponse struct {
	Accounts []Account `json:"accounts"`
}

// ListMyGamesResponse defines model for ListMyGamesResponse.
type ListMyGamesResponse struct {
	Games []MyGame `json:"games"`
}

// ListSessionsResponse defines model for ListSessionsResponse.
type ListSessionsResponse struct {
	Sessions []Session `json:"sessions"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Matched case-insensitively; stored lowercased.
	Email  openapi_types.Email `json:"email"`
	Secret string              `json:"secret"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// AllSessions Revoke every session for the account rather than just the current one.
	AllSessions *bool `json:"allSessions,omitempty"`
}

// MyGame A game the caller holds a seat in, projected with the caller's seat. Grounded in `memberships` joined to `games`; carries only game identity (`games.code`), no engine state.
type MyGame struct {
	// Code The game's human-facing slug (`games.code`).
	Code string `json:"code"`

	// Id The game's id (`games.id`).
	Id int64 `json:"id"`

	// IsGm Whether the caller is the GM of this game (`memberships.is_gm`).
	IsGm bool `json:"isGm"`

	// PlayerId The caller's seat id in this game (`memberships.id`).
	PlayerId int64 `json:"playerId"`
}

// PurgeSessionsResponse defines model for PurgeSessionsResponse.
type PurgeSessionsResponse struct {
	// Purged Number of expired session records removed.
	Purged int64 `json:"purged"`
}

// Session An active session (neither revoked nor expired). Raw tokens are never included.
type Session struct {
	// Current True for the session behind the current request (self listings only).
	Current   *bool     `json:"current,omitempty"`
	ExpiresAt time.Time `json:"expiresAt"`

	// Id Opaque session identifier.
	Id       string    `json:"id"`
	IssuedAt time.Time `json:"issuedAt"`
}

// UpdateAccountRequest Partial update; a present field is set, an absent field is left unchanged. At least one field is required.
type UpdateAccountRequest struct {
	DisplayName *string `json:"displayName,omitempty"`

	// Email Lowercased and must remain unique.
	Email    *openapi_types.Email `json:"email,omitempty"`
	IsActive *bool                `json:"isActive,omitempty"`
	IsAdmin  *bool                `json:"isAdmin,omitempty"`

	// Secret New secret (at least 8 characters); the admin-only recovery path.
	Secret *string `json:"secret,omitempty"`
}

// UpdateMeRequest Non-sensitive profile fields the caller may set on themselves.
type UpdateMeRequest struct {
	DisplayName string `json:"displayName"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Application Server application version (semver, with pre-release when set).
	Application string          `json:"application"`
	Database    DatabaseVersion `json:"database"`
}

// AccountId defines model for AccountId.
type AccountId = int64

// SessionId defines model for SessionId.
type SessionId = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// sessionTokenContextKey is the context key for sessionToken security scheme
type sessionTokenContextKey string

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// UpdateMyEmailJSONRequestBody defines body for UpdateMyEmail for application/json ContentType.
type UpdateMyEmailJSONRequestBody = ChangeEmailRequest

// UpdateMySecretJSONRequestBody defines body for UpdateMySecret for application/json ContentType.
type UpdateMySecretJSONRequestBody = ChangeSecretRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List accounts
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)
	// Create an account
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// Get an account by id
	// (GET /accounts/{accountId})
	GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Revoke all of an account's sessions
	// (DELETE /accounts/{accountId}/sessions)
	RevokeAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// List an account's active sessions
	// (GET /accounts/{accountId}/sessions)
	ListAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Revoke one of an account's sessions
	// (DELETE /accounts/{accountId}/sessions/{sessionId})
	RevokeAccountSession(w http.ResponseWriter, r *http.Request, accountId AccountId, sessionId SessionId)
	// Purge expired sessions
	// (POST /admin/sessions/purge)
	PurgeSessions(w http.ResponseWriter, r *http.Request)
	// Exchange credentials for a session token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the current session (or all of the account's sessions)
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Liveness check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get the authenticated account
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Update the authenticated account's own profile
	// (PATCH /me)
	UpdateMe(w http.ResponseWriter, r *http.Request)
	// Change the authenticated account's email
	// (POST /me/email)
	UpdateMyEmail(w http.ResponseWriter, r *http.Request)
	// List the games the authenticated account holds a seat in
	// (GET /me/games)
	ListMyGames(w http.ResponseWriter, r *http.Request)
	// Change the authenticated account's secret
	// (POST /me/secret)
	UpdateMySecret(w http.ResponseWriter, r *http.Request)
	// List the authenticated account's active sessions
	// (GET /me/sessions)
	ListMySessions(w http.ResponseWriter, r *http.Request)
	// Revoke one of the authenticated account's sessions
	// (DELETE /me/sessions/{sessionId})
	RevokeMySession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Application and database schema version
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeAccountSessions operation middleware
func (siw *ServerInterfaceWrapper) RevokeAccountSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeAccountSessions(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccountSessions operation middleware
func (siw *ServerInterfaceWrapper) ListAccountSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountSessions(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeAccountSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeAccountSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeAccountSession(w, r, accountId, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeSessions operation middleware
func (siw *ServerInterfaceWrapper) PurgeSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMyEmail operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyEmail(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMyEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyGames operation middleware
func (siw *ServerInterfaceWrapper) ListMyGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMySecret operation middleware
func (siw *ServerInterfaceWrapper) UpdateMySecret(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMySecret(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMySessions operation middleware
func (siw *ServerInterfaceWrapper) ListMySessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMySessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeMySession operation middleware
func (siw *ServerInterfaceWrapper) RevokeMySession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeMySession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts", wrapper.ListAccounts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts", wrapper.CreateAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{accountId}", wrapper.GetAccount)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/accounts/{accountId}", wrapper.UpdateAccount)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/accounts/{accountId}/sessions", wrapper.RevokeAccountSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{accountId}/sessions", wrapper.ListAccountSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/accounts/{accountId}/sessions/{sessionId}", wrapper.RevokeAccountSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/sessions/purge", wrapper.PurgeSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/me", wrapper.UpdateMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/me/email", wrapper.UpdateMyEmail)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me/games", wrapper.ListMyGames)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/me/secret", wrapper.UpdateMySecret)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me/sessions", wrapper.ListMySessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/me/sessions/{sessionId}", wrapper.RevokeMySession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListAccountsRequestObject struct {
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse ListAccountsResponse

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAccounts401JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListAccounts403JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse CreateAccountResponse

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAccount401JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateAccount403JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount409JSONResponse struct{ ConflictJSONResponse }

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse AccountResponse

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAccount401JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAccount403JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAccount404JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
	Body      *UpdateAccountJSONRequestBody
}

type UpdateAccountResponseObject interface {
	VisitUpdateAccountResponse(w http.ResponseWriter) error
}

type UpdateAccount200JSONResponse AccountResponse

func (response UpdateAccount200JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateAccount400JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateAccount401JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateAccount403JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAccount404JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateAccount409JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessionsRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type RevokeAccountSessionsResponseObject interface {
	VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error
}

type RevokeAccountSessions204Response struct {
}

func (response RevokeAccountSessions204Response) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeAccountSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeAccountSessions401JSONResponse) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessions403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeAccountSessions403JSONResponse) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessions404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeAccountSessions404JSONResponse) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessionsRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type ListAccountSessionsResponseObject interface {
	VisitListAccountSessionsResponse(w http.ResponseWriter) error
}

type ListAccountSessions200JSONResponse ListSessionsResponse

func (response ListAccountSessions200JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAccountSessions401JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessions403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListAccountSessions403JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessions404JSONResponse struct{ NotFoundJSONResponse }

func (response ListAccountSessions404JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessionRequestObject struct {
	AccountId AccountId `json:"accountId"`
	SessionId SessionId `json:"sessionId"`
}

type RevokeAccountSessionResponseObject interface {
	VisitRevokeAccountSessionResponse(w http.ResponseWriter) error
}

type RevokeAccountSession204Response struct {
}

func (response RevokeAccountSession204Response) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeAccountSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeAccountSession401JSONResponse) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSession403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeAccountSession403JSONResponse) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSession404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeAccountSession404JSONResponse) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeSessionsRequestObject struct {
}

type PurgeSessionsResponseObject interface {
	VisitPurgeSessionsResponse(w http.ResponseWriter) error
}

type PurgeSessions200JSONResponse PurgeSessionsResponse

func (response PurgeSessions200JSONResponse) VisitPurgeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PurgeSessions401JSONResponse) VisitPurgeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeSessions403JSONResponse struct{ ForbiddenJSONResponse }

func (response PurgeSessions403JSONResponse) VisitPurgeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthSession

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse AccountResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse AccountResponse

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmailRequestObject struct {
	Body *UpdateMyEmailJSONRequestBody
}

type UpdateMyEmailResponseObject interface {
	VisitUpdateMyEmailResponse(w http.ResponseWriter) error
}

type UpdateMyEmail200JSONResponse AccountResponse

func (response UpdateMyEmail200JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmail400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMyEmail400JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmail401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMyEmail401JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmail409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateMyEmail409JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyGamesRequestObject struct {
}

type ListMyGamesResponseObject interface {
	VisitListMyGamesResponse(w http.ResponseWriter) error
}

type ListMyGames200JSONResponse ListMyGamesResponse

func (response ListMyGames200JSONResponse) VisitListMyGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyGames401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMyGames401JSONResponse) VisitListMyGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMySecretRequestObject struct {
	Body *UpdateMySecretJSONRequestBody
}

type UpdateMySecretResponseObject interface {
	VisitUpdateMySecretResponse(w http.ResponseWriter) error
}

type UpdateMySecret204Response struct {
}

func (response UpdateMySecret204Response) VisitUpdateMySecretResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateMySecret400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMySecret400JSONResponse) VisitUpdateMySecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMySecret401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMySecret401JSONResponse) VisitUpdateMySecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListMySessionsRequestObject struct {
}

type ListMySessionsResponseObject interface {
	VisitListMySessionsResponse(w http.ResponseWriter) error
}

type ListMySessions200JSONResponse ListSessionsResponse

func (response ListMySessions200JSONResponse) VisitListMySessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMySessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMySessions401JSONResponse) VisitListMySessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeMySessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type RevokeMySessionResponseObject interface {
	VisitRevokeMySessionResponse(w http.ResponseWriter) error
}

type RevokeMySession204Response struct {
}

func (response RevokeMySession204Response) VisitRevokeMySessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeMySession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeMySession401JSONResponse) VisitRevokeMySessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeMySession404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeMySession404JSONResponse) VisitRevokeMySessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List accounts
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// Create an account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// Get an account by id
	// (GET /accounts/{accountId})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(ctx context.Context, request UpdateAccountRequestObject) (UpdateAccountResponseObject, error)
	// Revoke all of an account's sessions
	// (DELETE /accounts/{accountId}/sessions)
	RevokeAccountSessions(ctx context.Context, request RevokeAccountSessionsRequestObject) (RevokeAccountSessionsResponseObject, error)
	// List an account's active sessions
	// (GET /accounts/{accountId}/sessions)
	ListAccountSessions(ctx context.Context, request ListAccountSessionsRequestObject) (ListAccountSessionsResponseObject, error)
	// Revoke one of an account's sessions
	// (DELETE /accounts/{accountId}/sessions/{sessionId})
	RevokeAccountSession(ctx context.Context, request RevokeAccountSessionRequestObject) (RevokeAccountSessionResponseObject, error)
	// Purge expired sessions
	// (POST /admin/sessions/purge)
	PurgeSessions(ctx context.Context, request PurgeSessionsRequestObject) (PurgeSessionsResponseObject, error)
	// Exchange credentials for a session token
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the current session (or all of the account's sessions)
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Liveness check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get the authenticated account
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Update the authenticated account's own profile
	// (PATCH /me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
	// Change the authenticated account's email
	// (POST /me/email)
	UpdateMyEmail(ctx context.Context, request UpdateMyEmailRequestObject) (UpdateMyEmailResponseObject, error)
	// List the games the authenticated account holds a seat in
	// (GET /me/games)
	ListMyGames(ctx context.Context, request ListMyGamesRequestObject) (ListMyGamesResponseObject, error)
	// Change the authenticated account's secret
	// (POST /me/secret)
	UpdateMySecret(ctx context.Context, request UpdateMySecretRequestObject) (UpdateMySecretResponseObject, error)
	// List the authenticated account's active sessions
	// (GET /me/sessions)
	ListMySessions(ctx context.Context, request ListMySessionsRequestObject) (ListMySessionsResponseObject, error)
	// Revoke one of the authenticated account's sessions
	// (DELETE /me/sessions/{sessionId})
	RevokeMySession(ctx context.Context, request RevokeMySessionRequestObject) (RevokeMySessionResponseObject, error)
	// Application and database schema version
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request) {
	var request ListAccountsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request GetAccountRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccount operation middleware
func (sh *strictHandler) UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request UpdateAccountRequestObject

	request.AccountId = accountId

	var body UpdateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccount(ctx, request.(UpdateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountResponseObject); ok {
		if err := validResponse.VisitUpdateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeAccountSessions operation middleware
func (sh *strictHandler) RevokeAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request RevokeAccountSessionsRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeAccountSessions(ctx, request.(RevokeAccountSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeAccountSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeAccountSessionsResponseObject); ok {
		if err := validResponse.VisitRevokeAccountSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAccountSessions operation middleware
func (sh *strictHandler) ListAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request ListAccountSessionsRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccountSessions(ctx, request.(ListAccountSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccountSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountSessionsResponseObject); ok {
		if err := validResponse.VisitListAccountSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeAccountSession operation middleware
func (sh *strictHandler) RevokeAccountSession(w http.ResponseWriter, r *http.Request, accountId AccountId, sessionId SessionId) {
	var request RevokeAccountSessionRequestObject

	request.AccountId = accountId
	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeAccountSession(ctx, request.(RevokeAccountSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeAccountSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeAccountSessionResponseObject); ok {
		if err := validResponse.VisitRevokeAccountSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PurgeSessions operation middleware
func (sh *strictHandler) PurgeSessions(w http.ResponseWriter, r *http.Request) {
	var request PurgeSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PurgeSessions(ctx, request.(PurgeSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PurgeSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PurgeSessionsResponseObject); ok {
		if err := validResponse.VisitPurgeSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(w http.ResponseWriter, r *http.Request) {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMyEmail operation middleware
func (sh *strictHandler) UpdateMyEmail(w http.ResponseWriter, r *http.Request) {
	var request UpdateMyEmailRequestObject

	var body UpdateMyEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMyEmail(ctx, request.(UpdateMyEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMyEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMyEmailResponseObject); ok {
		if err := validResponse.VisitUpdateMyEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyGames operation middleware
func (sh *strictHandler) ListMyGames(w http.ResponseWriter, r *http.Request) {
	var request ListMyGamesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyGames(ctx, request.(ListMyGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMyGamesResponseObject); ok {
		if err := validResponse.VisitListMyGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMySecret operation middleware
func (sh *strictHandler) UpdateMySecret(w http.ResponseWriter, r *http.Request) {
	var request UpdateMySecretRequestObject

	var body UpdateMySecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMySecret(ctx, request.(UpdateMySecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMySecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMySecretResponseObject); ok {
		if err := validResponse.VisitUpdateMySecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMySessions operation middleware
func (sh *strictHandler) ListMySessions(w http.ResponseWriter, r *http.Request) {
	var request ListMySessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMySessions(ctx, request.(ListMySessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMySessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMySessionsResponseObject); ok {
		if err := validResponse.VisitListMySessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeMySession operation middleware
func (sh *strictHandler) RevokeMySession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request RevokeMySessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeMySession(ctx, request.(RevokeMySessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeMySession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeMySessionResponseObject); ok {
		if err := validResponse.VisitRevokeMySessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hxtc9s4kv9X6eL/XxXbR8vOJHW1Z7/yzGazvkoy2diz+yJJRRDZkjAhAQ4AWtGmXHUf4j7hfZKrboBP",
	"EijZSZzZqbp3CU0CDfTzr7v1Ocl0WWmFytnk7HNSCSNKdGj4fxdZpmvlLnP6T442M7JyUqvkLLlQIPxf",
	"H1lYFHomimJ9XCv5W40gcziYhj/bicynh5MkTSR9Vwm3TNJEiRKTs0S0G6SJwd9qaTBPzpypMU1stsRS",
	"0M5zbUrhkrNEKvfvT5M0KaWSZV0mZ4/TxK0r9H/CBZrk9jZNrtBaqVWM7J8rQQRa/wbIHJWTc4kGDqbh",
	"4U6Cbbv0LoJLqV6gWrhln0LrjFSL5JYoNGgrrSzyLf8o8jf4W43W0f8yrRwq/qeoqkJmgkg/+dUS/Z97",
	"m/x/g/PkLPl/Jx0HT/xf7ckzY7TxWw3Pf6luRCFzMGHD2zT5Sat5IbPvsHk4JWRhRwsr6ZaQ1cagcmCd",
	"cEgU/UWbmcxzVA9P0kXtliQCmXCYw6x2oLQDURR6hTk4TUKO1oJbSgsGra5NxjS+0u4vulb597g1vyus",
	"hGXq5rzvbZr8okTtltrIf+J3oOOltFaqRQr4qSKxT0EbkEGeMoOsSqKwrIJhtZ4RiZuQjszjXJdCtlal",
	"Z0Cm4MSswMMJTKW9yEupplBKIpP4QspsbtAcF3iDBb3yQfh35oVYnIN0oPAGDWTCGIkWKjTHC1EiGF2g",
	"TWG1lNkShEGwtZmLjORgDdPnz67hpMQTetVOyRxURldonPRamxkkmblwAwuVC4fHTpaYbOl9muTSVoVY",
	"v2JTsnkbf9UrPk2FxmoFK6GcJQGcIYg8N2gt5udQijU9wbJy60lsDyyFLAYk+SeRV2UeNa6bBjVNpL3I",
	"nLyJEH29RFC4YAaCnnt2OG0wh6lUgr/yjOgRO9O6QKHCysSr7YWv+jxlfkrrjHDaDDxLw+vD+PJ1ld+P",
	"R7d9q/6Wbiht76+9hY7s9+0CevYrZmxOg7i/CRaenepAcESnD7v0sFGbTZqaz6N7124ZnN/2vl5t7UVE",
	"E/+xRBVUyfvF8C7d6t1E2+mPqPa6W37rHCqDlgy+sCBghsKQdrYGZAJXS71SoFWGk9G9rvnp5wQVxQFv",
	"kx95md6tjLDUE9pfJO3dTOxSf1oKtcBnJAU9N71hDLwLu8LMoIurSSaKAs0j27k7fjmFGzQUgeQww7k2",
	"yHzIeM/B9VfC2pU2uQ9/xsOLNFG4etZYgSEdr3AFLM7nQA7OZMJiDkLlUNbWkWHxAdxg40b+dwc1w1se",
	"3kePpPEL9u9+zQ138Sh+ktZJtXjQO95FisGqEBmWHZ/hQDgoUFgHf6Ktjcgoyj68w/5/+oLbDv+OXjc7",
	"rtZMjdz3hq/acx0Yl7cX31bINj3RXNSFS87morC417vse9mOsPNn/ocozkHOQZfSUaAowAiV6xK0QpAW",
	"FqjQcAhJ5zToaqMwb03Y1zIYx3VnyMxv5XPSpD3RLjGvCkFhwqfOmDWmXatiDStyK3RDFLm2C/bt+7l/",
	"UToLs8ysKwdLYZd0oz6KmOx10bvc4Z+FEzNh8e9o4i7Rn7v3582Id2E4tLE+UPUZAdkOXaGCPCwPB1d/",
	"eyEdQm3RfLjxq7Fi4ydRVgUmZ0/TQZz15Id+EnsaTWL7hxzSGTuqj9q3fX78cabzSDB3xWF2CqXIllLh",
	"sUGR0xPgVYA+Ghwqqfv5R0RbS7RWLGKxbl0K1Vv/U1UIxTc93GAQN5BUlD4H6WUesX1DchvL/3/SxmDh",
	"41WZw1wb5mf4IuUHtq4qbRyrcqEX4IzIpFrsl0W+1u7Y23zaVGvmToydL6R1QRntXq3mf0uHpb2Hfoct",
	"hTFiPaZUdpS2l+vnlBaNk8ZZ053p8svtJcsvOkZTCHx3ENUAPHemq4ml9xHWLhylTS+kGvWzI57zpXDZ",
	"EnMg53kslUVlJTm+Yn3eJFhdBPclnrRzd/eOfqLOqV1x5Ap0PR5riKK46rFm01dvwiE3+iMCpfTrNrFo",
	"9LgBD4xwS6RHQsGvFHVwwBcCb60wli7eRggPgrkNXQAjCK6N62Gpi5zSGYvCgVTkCTWtgrkHuVw/BaCX",
	"JvDc6FrlmINUMC2xnKGxS1nZKfyqpfLOZurhh/MWvWB/yZt77NKt4cC/NCHzMz1MQWlAtZAKPaIWgS6i",
	"5p8cOi30yMKS7fOczR7Yol5s7DEZhxNG12RM2C/S4Kt3gh6el9F8NfC3vX/psaDnLz0MQTEZXdJB/2In",
	"0n5YlGNgAYW7aC7zPembZzAzbXSbu54vBjcEJ9JSE+4gplava0N50z6zV9FrkWO9qolkuq+A6LXqZDDT",
	"JrdgsNQ33r60TvnxD+kOQH5/LBOoiZ2nB11Eig1k/loKDxRKFgHD5iAHpU1zjMMJvBErHzRYBvY8AChV",
	"VtS5P040uYxw3tTYGpdm7xkupcoHJiXED3BgsZhD4bNPr6wj0jZAY+6Gscj71DPiKmpt/bVwWLvGPtzk",
	"FwbftvPM4QFeC+OkKMBDdecg2hRiLrHIORWgxEIoELPh8wLnDmrl8/h8AhdNgk0pR/tWc4Btrm+kuF+T",
	"1Bpk7HpHYrszld2Zut49VX2Fqz1ow7n3krT0MXsS0nT2pJVwyy9NVUdY/xJHuf5Kq+M2piFXOZdF4Jnt",
	"W/VSkI8njtLT0mJx41HJLwcrNmS6/2lMikPStSMI70oYYzB2v8wBIT8kU1HeoEl9eFAZyreIY+jTZotu",
	"mEImp5PHTyaPj2foRLS4ELLRfTHtZlK8Ffv3ztNbNZrMWMxqI936itYexNjXcTz4QoFmi5U2VRsr8w18",
	"GEpyHb4Ic0IJ5klBEfSUtS0YB9I9C9OLkH4ytWfgMWB4V5+ePsl4Lf4nTifwSjsQ8J//uIb/+a//Buna",
	"eEppyAohSzuBS0f2YikXy2NUzuhqzVuGcPvoSNhjaVMuwS2FXWJ+dAQHtSrkRx8JBgSjK080KvSBXp8G",
	"5fPn5loiCTPRMlsD/laLgoI5sRBShYC1rUiHChipgY9723zVavaAQbakBVmWmEsK++CivVfRq3JaL1/T",
	"4Dg/CAeXV/Dqlxcv4OLVnxvknx77ywOlV1z+YgFiS+Sh9lYgls5VvmAo1VxvM/3Ns6truHh92TrS60ev",
	"6aQ9pfCXMoFriqhyndWMnIaYLpQ/Ka4ztVu2y6ykQci0ovzcncNSqLxAY1PICkkinwYwzrtmRgv8bhQS",
	"5EbeoIK50SW/li0xoziiuX/pJuCBaU9DhRnMpaE7d021hBGRd+qdYrIbxWaD6ik/Ouod8uioKTByXHAG",
	"dm0dllCiE6RmaZ9NTGYIMhouFnKO2TorMPVWfFC67sBvvVJ8K/jJ+RtokqJeGU1q1cj7opeF9KqprJe9",
	"EiwttCmPtiVxmL7MaEVh1kFqvTTMui3eXv3tBbDNEGBwjgZVhu8PJpOTUME+yXVmT9o/ndjfimNvvyZl",
	"fhiunK6Xg2+f7PSu94DTjBRcbZRNQZucxaIhdqVNQXIhcih1jsUh6w1vzEhvsWYdr4RxbTLRiBms0XFN",
	"uRAqp69AQCEcGiBl71I9TxMJtOc2dBfU5FVG1w5hiYYRZMEEeaccUsdeTbXNPoi5lIFYONioUB+eA5ek",
	"aWl+4qMTocTC72YpAqCt6HD4qdKWEWovS1u6SAfli74YCiWRGjfiR0cDM350NDTW0UrfL531bKS0DWD6",
	"iPBhOtCEFg+8l7H+3vb3DTHYJyC1CtYhBI1MRO6tD+OPWjuO2KVjX+8t5EWPKyGSuHh9maTJTYNYU1Aw",
	"OSX3rytUopLJWfJkcjp5QiGScEt2ySd9nHARCxw51mQ5ncAbLl5YEEXR8KTRIe+UJYfSFAIxZZQwD/DK",
	"ZKO96YfT02/WnBLFRWNtPQ0tt2ny9PTx2LItnSeDVhr+6Mn+j7o+JQ6G6rIUZh1uo7074qpYWAqtWqre",
	"36ZJpe0eTvjaDutbWCyFpqmCpUhpdcxGHWpVoLXcHxN6Lk56zTLc24JuAlPORqacPO0szcHlnKSfNJHf",
	"/oK6F6NaG1Wk6d56D3R9hRA6bNio6toxuMa2IROK9LrQC+CzO1k0BFlvOuZCFsdZwSYuwImH21I7KJ4l",
	"bd3gR52vv5nERqutt8Og25kab7e05vFD0bBXbZqb94pwul8Reh2M30vh6Iv/2P9F29w41FB/Iz3Nimvp",
	"bdoZz5PPbbPq7V0M6Za0PUfXF7UHspD34HKOTsjCfleWPd3/RdtZOWTZc3Q9fnlHNGpbe13Mb+P7da+c",
	"dF3Ot+/ZbWbL3Yb5GccALcKk2w6BLwavQqC+G8DaZ76HIBRcgMJVZ8UbCx8FhuCAo1wK7gqrN0GicOfH",
	"A7CIE2nXhK9Kg8VifkyBjcyQwiuMmdwBKPhAJjcKPN7J5P4uahiaFP/Vje29NPfrrLNn4Bdb5xM7KCYW",
	"6HBfyHujP6INsf1GpaFBG5wwC2zDukb64V0y1yZDCkYoRuElVqQV7xJeKawggC7A6FJy1mUgR96nn7tP",
	"4LJJHs5B5lhWmgRxW4k8veEm2srpljQ/jeGR/uWmbPIHsf2h5kspiZ735ILLce3xo65gb75DwbqNcPiR",
	"3ZAE67N5xg044SVSeKFGVDjZ5qa/c6iEND08wN83tHzk1m6HppSKRf0O4vHIQjEgZ1cWNi4V3zYZ26o+",
	"RgzdsDdz41L/IBLoUzq14xzfPBTZa95OPrfTSLf3NXUCrFSLojNzAWga6kAfQ6aMa4aFVgwnhT64xhqu",
	"feVm+vT06fSrzNh9rNgf04hRbHdfI/bFQpTufbmblQsSR8LSiRhX67notReu+DOLn91qIlgttUWYdoWF",
	"qY8zyZCuG0i4Etal9EkhZMldJ5XIcALPhp0JHGiSDKIZ4N8BiCv1DQvnEksQ8zlmzkLTKLChr9ww0EF3",
	"He5F1Ki2MyLSCTEU4kEPxkNa23izR8Tc8ovsT4gf+e8DgXkiNvpKBvLtB2h8ENcW+cYl7e++g5/RME6D",
	"4N8aOKgP2fZ0yiPBfZhJqDwFrcDWPNSXcqWxh2fHapKN0w/IVos878O2/T4zS5F61yBiJ8BzENzLOtri",
	"BwdbLX6HjIx16F8D1PSRsEhAwHf6MFnWoK3xe2dXvTmniAYwaZ7LmH/PzKpXEk/O3r7vK8SzTz7V709K",
	"hsxgUNXoq0jtlhsaoms3riKNbx/pVeok1gvxjFsruF4kne0XhKcT+AcFrtNeY+YZEFOnu3OkRixlm2AA",
	"aSaK3EcekTJJm0gxUQf2kLHbpi6l8FOrO1Hxpgt5MPnu9azebo9tR0MT/xVPDVdfbnxjcUO/3aztgiP5",
	"8UnRhvELXDuMi9MSReGW/xyFMT01XXGZ8g6FlqyenmHnK6c/nJ5OuySHx0GOeR5kpvM1TPXHKayWssAg",
	"gJpnqRkVM+SpuZKaa/Q1SafrzC/UdJ1EQdS/MvH7XS3RccIkDZneddToj+9UEp3P3+7ikRnjXKZWqmkj",
	"GlP1F81tcU9BjwNXXPAPPPCtStHr74cibeW3DcmvG6QuOj7drx2rYh1pd5HKjz/TJU/gdTMN7avKdxiD",
	"3mLIS/ydAe3rsW6Ib6F+z9GNt1v0mPsSQ6gehY+v+uCoR/y2avsq2hRHDAx6X6x9M/u017Q27c9Dh+cf",
	"FP3hcAJX7Wptszj3unRRindKnu85FnLG5bqCXAMlCQ59mwLJonANFL1hiygIO4Pp65+vvKgElJo7RtqH",
	"AYYeQ4SDDD0UGNy1Iv7r4cAkvQEDHsrt94pYNnHXfc1FQTI3Zd8btZO2azYepAwUwQfyYRAXfsRM1LZ5",
	"Gpq/OC1oxTcdNIeSLti6qoo1TAczsNNdE78h4uhVVvgHSaQp2+hktVx3VFBwRMf2/Tr9yRIRijRawfT1",
	"xfVPfyVJn/qMQTWj1ncotj/rxpVDcspN69q1UdSBj+k43ZG2qxuNVlherp+FxuMHKWpvj8T/n15tpc9f",
	"UZ7uGg/HFLHtK4+oYDt8tze68I1ikTGmYUNfO9SEIltG5pmmzbTK1Etq9zHI/NBjPML5URlSgFU3v7Nm",
	"WScde/4SDqbNhA5cZbrq5m39Tud37ZLrD+PApWqzlSbCCe0scQQ9zDY+NHK+OUI5IsHtmTxTv4GVZyh7",
	"yPyokG2OtI0IWzeMcAeD3zTwBIvfHdDbcYpQxy15H+eJoDs9Q6+6QQjZzm5P4OcW+tlIlzRL48D6BsvL",
	"wKKg7QrsCj0BdtG144pM3zg7HnZvWpdqlfu25l5/oyMfy96HJ6BhbtAu4aDX29Av/ljJvVT8W0CUtdPq",
	"fgSnoSJ4NXrFE7HDKbQ/EfFwXmH4Ox53cgtRiL8nKPnvFA/dwQzb5kLjqtHVoe+T6A2B6p2jbn2T3DSS",
	"MxxjMNMLJf/p4Z2RibgG1vQSeof5NoYtDRHRqGnAhcZM6b9aHXLslr+pYR0TlvGSYUxq7lreGy3pbVXr",
	"gqntWhcKvSAj5qPhHMlEv0uAyUXD/e9O94ZwdO2mZEWLdawpfcN4ZmJW4DkIBbX6qHqv8O/GcRVspTzI",
	"IJQOJZrQ5dovJw4iboM3KIoGsuSf+UGV4QQu2zpjD3DyxRv+RTVpnR2rQLZS+p2Lj9+qlLjbPsVl7b41",
	"xc0y4U33myl7LVvAzEJ15ZGNjsO1wy5+LKR5HI4X/b0VCjz7P7kyTX0bfyPuXRWv3Pohl8MJvK5nhczO",
	"QenNwZv+yOgW2tXMzT2gQducOYzYsvAKSOUHNptJvjFMsj9KQFfd3uXwvqNg5XDZzRG/t+9vaSfmrRel",
	"jRLx60vwXOsNQZxHJyBSXxMjWWHYMcDUh0ma1KZIzpIT7tAMFG79qAy/3Y5XULjZeMTu91vDqW7Tz+M/",
	"BNrc0dbcVbcMY+nbi1zfbSyrW+clxkiJzmvBgWiL7Yc9SrpJh2hxPnx/0w6+9FqQRlbkyuzt+9v/DQAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
