//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionTokenScopes sessionTokenContextKey = "sessionToken.Scopes"
)

// Defines values for AuthSessionTokenType.
const (
	Bearer AuthSessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthSessionTokenType enum.
func (e AuthSessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Account An application-domain account (`accounts` table). `isAdmin` mirrors the server-level `is_admin` flag; it never carries per-game roles, which are surfaced by `GET /me/games`.
type Account struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DisplayName How the person wants to be addressed; may be empty.
	DisplayName *string             `json:"displayName,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Id          int64               `json:"id"`

	// IsActive The negation of the stored `inactive` flag.
	IsActive bool `json:"isActive"`

	// IsAdmin Server-level administrator (`accounts.is_admin`).
	IsAdmin   bool       `json:"isAdmin"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	// Account An application-domain account (`accounts` table). `isAdmin` mirrors the server-level `is_admin` flag; it never carries per-game roles, which are surfaced by `GET /me/games`.
	Account Account `json:"account"`
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	// ExpiresAt When the session expires.
	ExpiresAt time.Time `json:"expiresAt"`

	// Token Opaque session token; present as a bearer credential. Shown once.
	Token     string               `json:"token"`
	TokenType AuthSessionTokenType `json:"tokenType"`
}

// AuthSessionTokenType defines model for AuthSession.TokenType.
type AuthSessionTokenType string

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	// CurrentSecret The caller's current secret, verified before the change.
	CurrentSecret string `json:"currentSecret"`

	// NewEmail New email; lowercased and must be unique.
	NewEmail openapi_types.Email `json:"newEmail"`
}

// ChangeSecretRequest defines model for ChangeSecretRequest.
type ChangeSecretRequest struct {
	// CurrentSecret The account's existing secret, verified before the change.
	CurrentSecret string `json:"currentSecret"`

	// NewSecret The replacement secret (at least 8 characters).
	NewSecret string `json:"newSecret"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	DisplayName *string `json:"displayName,omitempty"`

	// Email Lowercased and must be unique.
	Email    openapi_types.Email `json:"email"`
	IsActive *bool               `json:"isActive,omitempty"`
	IsAdmin  *bool               `json:"isAdmin,omitempty"`

	// Secret Optional; if omitted a random one is generated and returned once.
	Secret *string `json:"secret,omitempty"`
}

// CreateAccountResponse defines model for CreateAccountResponse.
type CreateAccountResponse struct {
	// Account An application-domain account (`accounts` table). `isAdmin` mirrors the server-level `is_admin` flag; it never carries per-game roles, which are surfaced by `GET /me/games`.
	Account Account `json:"account"`

	// GeneratedSecret The plaintext secret, present only when one was generated. Shown once; only its bcrypt hash is stored.
	GeneratedSecret *string `json:"generatedSecret,omitempty"`
}

// DatabaseVersion defines model for DatabaseVersion.
type DatabaseVersion struct {
	// SchemaVersion Migrations applied to the open database (SQLite user_version).
	SchemaVersion int32 `json:"schemaVersion"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Stable, machine-readable error code.
		Code string `json:"code"`

		// Message Human-readable explanation.
		Message string `json:"message"`

		// RequestId Correlation id for the request, for support and log tracing.
		RequestId *string `json:"requestId,omitempty"`
	} `json:"error"`
}

// ListAccountsResponse defines model for ListAccountsResponse.
type ListAccountsResponse struct {
	Accounts []Account `json:"accounts"`
}

// ListMyGamesResponse defines model for ListMyGamesResponse.
type ListMyGamesResponse struct {
	Games []MyGame `json:"games"`
}

// ListSessionsResponse defines model for ListSessionsResponse.
type ListSessionsResponse struct {
	Sessions []Session `json:"sessions"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Matched case-insensitively; stored lowercased.
	Email  openapi_types.Email `json:"email"`
	Secret string              `json:"secret"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// AllSessions Revoke every session for the account rather than just the current one.
	AllSessions *bool `json:"allSessions,omitempty"`
}

// MyGame A game the caller holds a seat in, projected with the caller's seat. Grounded in `memberships` joined to `games`; carries only game identity (`games.code`), no engine state.
type MyGame struct {
	// Code The game's human-facing slug (`games.code`).
	Code string `json:"code"`

	// Id The game's id (`games.id`).
	Id int64 `json:"id"`

	// IsGm Whether the caller is the GM of this game (`memberships.is_gm`).
	IsGm bool `json:"isGm"`

	// PlayerId The caller's seat id in this game (`memberships.id`).
	PlayerId int64 `json:"playerId"`
}

// PurgeSessionsResponse defines model for PurgeSessionsResponse.
type PurgeSessionsResponse struct {
	// Purged Number of expired session records removed.
	Purged int64 `json:"purged"`
}

// Session An active session (neither revoked nor expired). Raw tokens are never included.
type Session struct {
	// Current True for the session behind the current request (self listings only).
	Current   *bool     `json:"current,omitempty"`
	ExpiresAt time.Time `json:"expiresAt"`

	// Id Opaque session identifier.
	Id       string    `json:"id"`
	IssuedAt time.Time `json:"issuedAt"`
}

// UpdateAccountRequest Partial update; a present field is set, an absent field is left unchanged. At least one field is required.
type UpdateAccountRequest struct {
	DisplayName *string `json:"displayName,omitempty"`

	// Email Lowercased and must remain unique.
	Email    *openapi_types.Email `json:"email,omitempty"`
	IsActive *bool                `json:"isActive,omitempty"`
	IsAdmin  *bool                `json:"isAdmin,omitempty"`

	// Secret New secret (at least 8 characters); the admin-only recovery path.
	Secret *string `json:"secret,omitempty"`
}

// UpdateMeRequest Non-sensitive profile fields the caller may set on themselves.
type UpdateMeRequest struct {
	DisplayName string `json:"displayName"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// Application Server application version (semver, with pre-release when set).
	Application string          `json:"application"`
	Database    DatabaseVersion `json:"database"`
}

// AccountId defines model for AccountId.
type AccountId = int64

// SessionId defines model for SessionId.
type SessionId = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// sessionTokenContextKey is the context key for sessionToken security scheme
type sessionTokenContextKey string

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// UpdateMyEmailJSONRequestBody defines body for UpdateMyEmail for application/json ContentType.
type UpdateMyEmailJSONRequestBody = ChangeEmailRequest

// UpdateMySecretJSONRequestBody defines body for UpdateMySecret for application/json ContentType.
type UpdateMySecretJSONRequestBody = ChangeSecretRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List accounts
	// (GET /accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)
	// Create an account
	// (POST /accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request)
	// Get an account by id
	// (GET /accounts/{accountId})
	GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Revoke all of an account's sessions
	// (DELETE /accounts/{accountId}/sessions)
	RevokeAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// List an account's active sessions
	// (GET /accounts/{accountId}/sessions)
	ListAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId)
	// Revoke one of an account's sessions
	// (DELETE /accounts/{accountId}/sessions/{sessionId})
	RevokeAccountSession(w http.ResponseWriter, r *http.Request, accountId AccountId, sessionId SessionId)
	// Purge expired sessions
	// (POST /admin/sessions/purge)
	PurgeSessions(w http.ResponseWriter, r *http.Request)
	// Exchange credentials for a session token
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the current session (or all of the account's sessions)
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Liveness check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get the authenticated account
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Update the authenticated account's own profile
	// (PATCH /me)
	UpdateMe(w http.ResponseWriter, r *http.Request)
	// Change the authenticated account's email
	// (POST /me/email)
	UpdateMyEmail(w http.ResponseWriter, r *http.Request)
	// List the games the authenticated account holds a seat in
	// (GET /me/games)
	ListMyGames(w http.ResponseWriter, r *http.Request)
	// Change the authenticated account's secret
	// (POST /me/secret)
	UpdateMySecret(w http.ResponseWriter, r *http.Request)
	// List the authenticated account's active sessions
	// (GET /me/sessions)
	ListMySessions(w http.ResponseWriter, r *http.Request)
	// Revoke one of the authenticated account's sessions
	// (DELETE /me/sessions/{sessionId})
	RevokeMySession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Application and database schema version
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeAccountSessions operation middleware
func (siw *ServerInterfaceWrapper) RevokeAccountSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeAccountSessions(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccountSessions operation middleware
func (siw *ServerInterfaceWrapper) ListAccountSessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccountSessions(w, r, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeAccountSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeAccountSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "accountId" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", r.PathValue("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeAccountSession(w, r, accountId, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PurgeSessions operation middleware
func (siw *ServerInterfaceWrapper) PurgeSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PurgeSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMyEmail operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyEmail(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMyEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyGames operation middleware
func (siw *ServerInterfaceWrapper) ListMyGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMySecret operation middleware
func (siw *ServerInterfaceWrapper) UpdateMySecret(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMySecret(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMySessions operation middleware
func (siw *ServerInterfaceWrapper) ListMySessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMySessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeMySession operation middleware
func (siw *ServerInterfaceWrapper) RevokeMySession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionTokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeMySession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts", wrapper.ListAccounts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/accounts", wrapper.CreateAccount)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{accountId}", wrapper.GetAccount)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/accounts/{accountId}", wrapper.UpdateAccount)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/accounts/{accountId}/sessions", wrapper.RevokeAccountSessions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/accounts/{accountId}/sessions", wrapper.ListAccountSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/accounts/{accountId}/sessions/{sessionId}", wrapper.RevokeAccountSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/sessions/purge", wrapper.PurgeSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/me", wrapper.UpdateMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/me/email", wrapper.UpdateMyEmail)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me/games", wrapper.ListMyGames)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/me/secret", wrapper.UpdateMySecret)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me/sessions", wrapper.ListMySessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/me/sessions/{sessionId}", wrapper.RevokeMySession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListAccountsRequestObject struct {
}

type ListAccountsResponseObject interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200JSONResponse ListAccountsResponse

func (response ListAccounts200JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAccounts401JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccounts403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListAccounts403JSONResponse) VisitListAccountsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccountRequestObject struct {
	Body *CreateAccountJSONRequestBody
}

type CreateAccountResponseObject interface {
	VisitCreateAccountResponse(w http.ResponseWriter) error
}

type CreateAccount201JSONResponse CreateAccountResponse

func (response CreateAccount201JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAccount400JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAccount401JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateAccount403JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAccount409JSONResponse struct{ ConflictJSONResponse }

func (response CreateAccount409JSONResponse) VisitCreateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type GetAccountResponseObject interface {
	VisitGetAccountResponse(w http.ResponseWriter) error
}

type GetAccount200JSONResponse AccountResponse

func (response GetAccount200JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAccount401JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAccount403JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAccount404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAccount404JSONResponse) VisitGetAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccountRequestObject struct {
	AccountId AccountId `json:"accountId"`
	Body      *UpdateAccountJSONRequestBody
}

type UpdateAccountResponseObject interface {
	VisitUpdateAccountResponse(w http.ResponseWriter) error
}

type UpdateAccount200JSONResponse AccountResponse

func (response UpdateAccount200JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateAccount400JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateAccount401JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateAccount403JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAccount404JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAccount409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateAccount409JSONResponse) VisitUpdateAccountResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessionsRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type RevokeAccountSessionsResponseObject interface {
	VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error
}

type RevokeAccountSessions204Response struct {
}

func (response RevokeAccountSessions204Response) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeAccountSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeAccountSessions401JSONResponse) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessions403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeAccountSessions403JSONResponse) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessions404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeAccountSessions404JSONResponse) VisitRevokeAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessionsRequestObject struct {
	AccountId AccountId `json:"accountId"`
}

type ListAccountSessionsResponseObject interface {
	VisitListAccountSessionsResponse(w http.ResponseWriter) error
}

type ListAccountSessions200JSONResponse ListSessionsResponse

func (response ListAccountSessions200JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAccountSessions401JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessions403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListAccountSessions403JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListAccountSessions404JSONResponse struct{ NotFoundJSONResponse }

func (response ListAccountSessions404JSONResponse) VisitListAccountSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSessionRequestObject struct {
	AccountId AccountId `json:"accountId"`
	SessionId SessionId `json:"sessionId"`
}

type RevokeAccountSessionResponseObject interface {
	VisitRevokeAccountSessionResponse(w http.ResponseWriter) error
}

type RevokeAccountSession204Response struct {
}

func (response RevokeAccountSession204Response) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeAccountSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeAccountSession401JSONResponse) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSession403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeAccountSession403JSONResponse) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeAccountSession404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeAccountSession404JSONResponse) VisitRevokeAccountSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeSessionsRequestObject struct {
}

type PurgeSessionsResponseObject interface {
	VisitPurgeSessionsResponse(w http.ResponseWriter) error
}

type PurgeSessions200JSONResponse PurgeSessionsResponse

func (response PurgeSessions200JSONResponse) VisitPurgeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PurgeSessions401JSONResponse) VisitPurgeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PurgeSessions403JSONResponse struct{ ForbiddenJSONResponse }

func (response PurgeSessions403JSONResponse) VisitPurgeSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthSession

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse AccountResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse AccountResponse

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmailRequestObject struct {
	Body *UpdateMyEmailJSONRequestBody
}

type UpdateMyEmailResponseObject interface {
	VisitUpdateMyEmailResponse(w http.ResponseWriter) error
}

type UpdateMyEmail200JSONResponse AccountResponse

func (response UpdateMyEmail200JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmail400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMyEmail400JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmail401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMyEmail401JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMyEmail409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateMyEmail409JSONResponse) VisitUpdateMyEmailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyGamesRequestObject struct {
}

type ListMyGamesResponseObject interface {
	VisitListMyGamesResponse(w http.ResponseWriter) error
}

type ListMyGames200JSONResponse ListMyGamesResponse

func (response ListMyGames200JSONResponse) VisitListMyGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyGames401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMyGames401JSONResponse) VisitListMyGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMySecretRequestObject struct {
	Body *UpdateMySecretJSONRequestBody
}

type UpdateMySecretResponseObject interface {
	VisitUpdateMySecretResponse(w http.ResponseWriter) error
}

type UpdateMySecret204Response struct {
}

func (response UpdateMySecret204Response) VisitUpdateMySecretResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateMySecret400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateMySecret400JSONResponse) VisitUpdateMySecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateMySecret401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateMySecret401JSONResponse) VisitUpdateMySecretResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListMySessionsRequestObject struct {
}

type ListMySessionsResponseObject interface {
	VisitListMySessionsResponse(w http.ResponseWriter) error
}

type ListMySessions200JSONResponse ListSessionsResponse

func (response ListMySessions200JSONResponse) VisitListMySessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMySessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMySessions401JSONResponse) VisitListMySessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeMySessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type RevokeMySessionResponseObject interface {
	VisitRevokeMySessionResponse(w http.ResponseWriter) error
}

type RevokeMySession204Response struct {
}

func (response RevokeMySession204Response) VisitRevokeMySessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeMySession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeMySession401JSONResponse) VisitRevokeMySessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeMySession404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeMySession404JSONResponse) VisitRevokeMySessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse VersionResponse

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List accounts
	// (GET /accounts)
	ListAccounts(ctx context.Context, request ListAccountsRequestObject) (ListAccountsResponseObject, error)
	// Create an account
	// (POST /accounts)
	CreateAccount(ctx context.Context, request CreateAccountRequestObject) (CreateAccountResponseObject, error)
	// Get an account by id
	// (GET /accounts/{accountId})
	GetAccount(ctx context.Context, request GetAccountRequestObject) (GetAccountResponseObject, error)
	// Update an account
	// (PATCH /accounts/{accountId})
	UpdateAccount(ctx context.Context, request UpdateAccountRequestObject) (UpdateAccountResponseObject, error)
	// Revoke all of an account's sessions
	// (DELETE /accounts/{accountId}/sessions)
	RevokeAccountSessions(ctx context.Context, request RevokeAccountSessionsRequestObject) (RevokeAccountSessionsResponseObject, error)
	// List an account's active sessions
	// (GET /accounts/{accountId}/sessions)
	ListAccountSessions(ctx context.Context, request ListAccountSessionsRequestObject) (ListAccountSessionsResponseObject, error)
	// Revoke one of an account's sessions
	// (DELETE /accounts/{accountId}/sessions/{sessionId})
	RevokeAccountSession(ctx context.Context, request RevokeAccountSessionRequestObject) (RevokeAccountSessionResponseObject, error)
	// Purge expired sessions
	// (POST /admin/sessions/purge)
	PurgeSessions(ctx context.Context, request PurgeSessionsRequestObject) (PurgeSessionsResponseObject, error)
	// Exchange credentials for a session token
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Revoke the current session (or all of the account's sessions)
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Liveness check
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Get the authenticated account
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Update the authenticated account's own profile
	// (PATCH /me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
	// Change the authenticated account's email
	// (POST /me/email)
	UpdateMyEmail(ctx context.Context, request UpdateMyEmailRequestObject) (UpdateMyEmailResponseObject, error)
	// List the games the authenticated account holds a seat in
	// (GET /me/games)
	ListMyGames(ctx context.Context, request ListMyGamesRequestObject) (ListMyGamesResponseObject, error)
	// Change the authenticated account's secret
	// (POST /me/secret)
	UpdateMySecret(ctx context.Context, request UpdateMySecretRequestObject) (UpdateMySecretResponseObject, error)
	// List the authenticated account's active sessions
	// (GET /me/sessions)
	ListMySessions(ctx context.Context, request ListMySessionsRequestObject) (ListMySessionsResponseObject, error)
	// Revoke one of the authenticated account's sessions
	// (DELETE /me/sessions/{sessionId})
	RevokeMySession(ctx context.Context, request RevokeMySessionRequestObject) (RevokeMySessionResponseObject, error)
	// Application and database schema version
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAccounts operation middleware
func (sh *strictHandler) ListAccounts(w http.ResponseWriter, r *http.Request) {
	var request ListAccountsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccounts(ctx, request.(ListAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccounts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountsResponseObject); ok {
		if err := validResponse.VisitListAccountsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAccount operation middleware
func (sh *strictHandler) CreateAccount(w http.ResponseWriter, r *http.Request) {
	var request CreateAccountRequestObject

	var body CreateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAccount(ctx, request.(CreateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAccountResponseObject); ok {
		if err := validResponse.VisitCreateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAccount operation middleware
func (sh *strictHandler) GetAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request GetAccountRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAccount(ctx, request.(GetAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAccountResponseObject); ok {
		if err := validResponse.VisitGetAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAccount operation middleware
func (sh *strictHandler) UpdateAccount(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request UpdateAccountRequestObject

	request.AccountId = accountId

	var body UpdateAccountJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAccount(ctx, request.(UpdateAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAccount")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAccountResponseObject); ok {
		if err := validResponse.VisitUpdateAccountResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeAccountSessions operation middleware
func (sh *strictHandler) RevokeAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request RevokeAccountSessionsRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeAccountSessions(ctx, request.(RevokeAccountSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeAccountSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeAccountSessionsResponseObject); ok {
		if err := validResponse.VisitRevokeAccountSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAccountSessions operation middleware
func (sh *strictHandler) ListAccountSessions(w http.ResponseWriter, r *http.Request, accountId AccountId) {
	var request ListAccountSessionsRequestObject

	request.AccountId = accountId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAccountSessions(ctx, request.(ListAccountSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAccountSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAccountSessionsResponseObject); ok {
		if err := validResponse.VisitListAccountSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeAccountSession operation middleware
func (sh *strictHandler) RevokeAccountSession(w http.ResponseWriter, r *http.Request, accountId AccountId, sessionId SessionId) {
	var request RevokeAccountSessionRequestObject

	request.AccountId = accountId
	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeAccountSession(ctx, request.(RevokeAccountSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeAccountSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeAccountSessionResponseObject); ok {
		if err := validResponse.VisitRevokeAccountSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PurgeSessions operation middleware
func (sh *strictHandler) PurgeSessions(w http.ResponseWriter, r *http.Request) {
	var request PurgeSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PurgeSessions(ctx, request.(PurgeSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PurgeSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PurgeSessionsResponseObject); ok {
		if err := validResponse.VisitPurgeSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(w http.ResponseWriter, r *http.Request) {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMyEmail operation middleware
func (sh *strictHandler) UpdateMyEmail(w http.ResponseWriter, r *http.Request) {
	var request UpdateMyEmailRequestObject

	var body UpdateMyEmailJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMyEmail(ctx, request.(UpdateMyEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMyEmail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMyEmailResponseObject); ok {
		if err := validResponse.VisitUpdateMyEmailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyGames operation middleware
func (sh *strictHandler) ListMyGames(w http.ResponseWriter, r *http.Request) {
	var request ListMyGamesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyGames(ctx, request.(ListMyGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMyGamesResponseObject); ok {
		if err := validResponse.VisitListMyGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMySecret operation middleware
func (sh *strictHandler) UpdateMySecret(w http.ResponseWriter, r *http.Request) {
	var request UpdateMySecretRequestObject

	var body UpdateMySecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMySecret(ctx, request.(UpdateMySecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMySecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMySecretResponseObject); ok {
		if err := validResponse.VisitUpdateMySecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMySessions operation middleware
func (sh *strictHandler) ListMySessions(w http.ResponseWriter, r *http.Request) {
	var request ListMySessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMySessions(ctx, request.(ListMySessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMySessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMySessionsResponseObject); ok {
		if err := validResponse.VisitListMySessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeMySession operation middleware
func (sh *strictHandler) RevokeMySession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request RevokeMySessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeMySession(ctx, request.(RevokeMySessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeMySession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeMySessionResponseObject); ok {
		if err := validResponse.VisitRevokeMySessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzvcts4kn+VLt5VxfbRsjPJbe3Znzyz2Yyvkkw29ux+SFIRRLYkTEiAA4BWtClX3UPcE96TXHUD/CeB",
	"kvPHmZmr+5bQJNBo9N9fd+tjkumy0gqVs8nZx6QSRpTo0PD/LrJM18pd5vSfHG1mZOWkVslZcqFA+L8+",
	"sLAo9EwUxfq4VvLXGkHmcDANf7YTmU8PJ0maSPquEm6ZpIkSJSZniWg3SBODv9bSYJ6cOVNjmthsiaWg",
	"nefalMIlZ4lU7k+PkzQppZJlXSZnD9PErSv0f8IFmuT2Nk2u0FqpVYzsnypBBFr/BsgclZNziQYOpuHh",
	"ToJtu/QugkupnqFauGWfQuuMVIvklig0aCutLDKXvxf5K/y1Ruvof5lWDhX/U1RVITNBpJ/8Yon+j71N",
	"/tXgPDlL/uWku8ET/1d78sQYbfxWw/NfqhtRyBxM2PA2TX7Qal7I7BtsHk4JWdjRwkq6JWS1MagcWCcc",
	"EkV/1WYm8xzV/ZN0UbsliUAmHOYwqx0o7UAUhV5hDk6TkKO14JbSgkGra5MxjS+0+6uuVf4tuOZ3hZWw",
	"TN2c971Nk5+VqN1SG/lP/AZ0PJfWSrVIAT9UJPYpaAMyyFNmkFVJFJZVMKzWMyJxE9KReZzrUsjWqvQM",
	"yBScmBV4OIGptBd5KdUUSklk0r2QMpsbNMcF3mBBr7wT/p15IRbnIB0ovEEDmTBGooUKzfFClAhGF2hT",
	"WC1ltgRhEGxt5iIjOVjD9OmTazgp8YRetVMyB5XRFRonvdZmBklmLtzAQuXC4bGTJSZbep8mubRVIdYv",
	"2JRscuNHveLTVGisVrASylkSwBmCyHOD1mJ+DqVY0xMsK7eexPbAUshiQJJ/EnlV5lHjumlQ00Tai8zJ",
	"mwjR10sEhQu+QNBzfx1OG8xhKpXgr/xF9IidaV2gUGFluqvtha/6d8r3Ka0zwmkz8CzNXR/Gl6+r/NPu",
	"6LZv1V8Th9KWfy0XOrLftgvo2S+YsTkN4v4qWHh2qgPBEZ0+7NLDRm02aWo+j+5du2Vwftv7erW1FxFN",
	"/McSVVAl7xfDu8TVu4m20+9R7XW3/NY5VAYtGXxhQcAMhSHtbA3IBK6WeqVAqwwno3td89OPCSqKA14n",
	"3/MyPa6MXKkntL9I2uNMjKk/LIVa4BOSgp6b3jAG3oVdYWbQxdUkE0WB5oHt3B2/nMINGopAcpjhXBvk",
	"e8h4zwH7K2HtSpvchz/j4UWaKFw9aazAkI4XuAIW53MgB2cyYTEHoXIoa+vIsPgAbrBxI/+7g5ohl4f8",
	"6JE0zmD/7pdwuItH8YO0TqrFvfJ4FykGq0JkWHb3DAfCQYHCOvgzbW1ERlH24R32//NncDv8O8pudlyt",
	"mRrh94av2sMOjMvbs68rZJueaC7qwiVnc1FY3Otd9r1sR67zJ/6HKM5BzkGX0lGgKMAIlesStEKQFhao",
	"0HAISec06GqjMG9N2JdeMI7rzvAyv5bPSZP2RLvEvCoEhQkfOmPWmHatijWsyK0QhyhybRfs2/dz/6J0",
	"FmaZWVcOlsIuiaM+ipjsddG73OFfhBMzYfHvaOIu0Z+79+fNiHdhOLSxPlD1GQHZDl2hgjwsDwdXf3sm",
	"HUJt0by78auxYuMHUVYFJmeP00Gc9ei7fhJ7Gk1i+4cc0hk7qo/at31+/HGm80gwd8VhdgqlyJZS4bFB",
	"kdMT4FWAPhocKqn7+UdEW0u0VixisW5dCtVb/0NVCMWcHm4wiBtIKkqfg/Qyj9i+IbmN5f8/aGOw8PGq",
	"zGGuDd9n+CLlB7auKm0cq3KhF+CMyKRa7JdFZmt37O172lRrvp3YdT6T1gVltHu1mv8tHZb2E/Q7bCmM",
	"EesxpbKjtD1fP6W0aJw0zpruTJdfbi9ZftExmkLgu4OoBuC5M11NLL2PsHbhKG16IdWonx3xnM+Fy5aY",
	"AznPY6ksKivJ8RXr8ybB6iK4z/Gknbv75Ogn6pzaFUdYoOvxWEMUxVXvajZ99SYccqPfI1BKv24Ti0aP",
	"G/DACLdEeiQU/EJRBwd8IfDWCmPp4m2E8CCY29AFMILg2rgelrrIKZ2xKBxIRZ5Q0yqYe5DL9VMAemkC",
	"T42uVY45SAXTEssZGruUlZ3CL1oq72ymHn44b9EL9pe8uccu3RoO/EsTMj/TwxSUBlQLqdAjahHoImr+",
	"yaHTQg8sLNk+z9nsgS3qxcYek3E4YXRNxoT9Ig2+eifo4WkZzVfD/bb8lx4LevrcwxAUkxGTDvqMnUj7",
	"blGOgQUU7qK5zPekb/6C+dJGt7nr+WJwQ3AiLTWBBzG1elkbypv2mb2KXosc60VNJBO/AqLXqpPBTJvc",
	"gsFS33j70jrlh9+lOwD5/bFMoCZ2nh50ESk2kPlrKTxQKFkEDJuDHJQ2zTEOJ/BKrHzQYBnY8wCgVFlR",
	"5/440eQycvOmxta4NHvPcClVPjApIX6AA4vFHAqffXplHZG2ARpzN4xFfko9I66i1tZfCoe1a+zDTX5m",
	"8G07zxwe4KUwTooCPFR3DqJNIeYSi5xTAUoshAIxGz4vcO6gVj6Pzydw0STYlHK0bzUH2L71jRT3S5Ja",
	"g4xd70hsd6ayO1PXu6eqL3C1B204916Slj5mT0Kazp60Em75uanqyNU/x9Fbf6HVcRvTkKucyyLcme1b",
	"9VKQj6cbpaelxeLGo5KfD1ZsyHT/05gUh6RrRxDelTDGYOx+mQNCfkimorxBk/rwoDKUb9GNoU+bLbph",
	"CpmcTh4+mjw8nqET0eJCyEb3xbSbSfFW7N87T2/VaDJjMauNdOsrWnsQY1/H8eALBZotVtpUbazMN/Bh",
	"KMl1+CLMCSWYJwVF0FPWtmAcSPcsTC9C+snUnoHHgOFNfXr6KOO1+J84ncAL7UDAf/7jGv7nv/4bpGvj",
	"KaUhK4Qs7QQuHdmLpVwsj1E5o6t1ClZ3CMXR0dWPF8ff/fufGKQ4OupgCjioVSHf+4AwABldlaLRpHf0",
	"2TTooGk8FK/SAiIpkOLSeVM+r/dcAQyB67baxSSg7cwlh4u0nAegrCZNoYPO1oC/1qKgSFEshFQhGm7L",
	"3aG8Rjrmg+o2Gbaa3WsQXGlBliXmkmJKuGgvTfRKqNYL7zR45XfCweUVvPj52TO4ePGXpqxAj/3NgNIr",
	"rq2xdLKZ8zh+K21L5ypfjZRqrrcl6tWTq2u4eHnZeunrBy/ppD2N8xwj7kkLuc5qhmVDwBhqqxQ0mtot",
	"22VW0iBkWlHy785hKVReoLEpZIUkfUoDo73fZyjC70bxRm7kDSqYG13ya9kSMwpSGv5LNwGPensaKsxg",
	"Lg3x3DWlGIZb3qg3islurAZba0/50VHvkEdHTfWS5fUM7No6LKFEJ0iH0/41MZkhgmlusZBzzNZZgal3",
	"EYO6eIesk5xymfmD8xxoMq5ejU5q1SjTopfi9Eq1rPS9+i4ttCmPtiVxmBvNaEVh1kFqvTTMui1eX/3t",
	"GbBBEmBwjgZVhm8PJpOTUB4/yXVmT9o/ndhfi2NvHCdlfhhYTuzlyN5nUj32HnAOk4KrjbIpaJOzWDTE",
	"rrQpSC5EDqXOsThkveGNGUYu1lzDr4RxbabSiBms0XHBuhAqp69AQCEcGiAT0uWRniZvDtg6dQxqkjaj",
	"a4ewRMPwtGCCvMcPeWmvYNumNnS5lN5YONgofx+eA9e7aWl+4kMfocTC72YpvKCt6HD4odKW4W8vS1u6",
	"SAdlRl8MhZJIjXuIo6OBjzg6GnqCaBnx584mN1LaRkcDuFnPidF61Zh9aCz2YTrQkdZef46P+L9h9l+R",
	"XPmkqlbBKIVAmCnMvdHjo2rtOAuRjuMXb5gvesIQoqOLl5dJmtw0KDwFOpNTCml0hUpUMjlLHk1OJ48o",
	"7BNuyWHGSR/7XMSCYY6f+WIm8IoLMhZEUTSi0KiuDzQkpwcU1jFllznF+T0MNtlo2fru9PSrNdxEsd5Y",
	"q1JDy22aPD59OLZsS+fJoD2IP3q0/6Ou94oDvLoshVkHbrS8o1sVC0vhYkvV29s0qbTdcxO+XsVqHhZL",
	"oWkU8ZKv1TH7EqhVgdZyz0/oIznpNQBxvw66CUw5w5pyQriz3AiXc5J+MgD89mfU8hip26iMTffWsKDr",
	"lYTQNcS2XNeOAUM2SZlQZDoLvQA+u5NFQ5D1FmsuZHGcFWxZA0R6uC21g4Jg0tZCvtf5+qtJbLSCfDtM",
	"JJyp8XZLax7eFw171abhvFeE0/2K0OvK/FYKR1/8x/4v2obNoYZ6jvQ0K66lt2lnPE8+tg24t3cxpFvS",
	"9hRdX9TuyUJ+wi3n6IQs7De9ssf7v2i7RYdX9hRd7768Ixq1rb3O7Nfx/bpXTrrO7du37Daz5W7D/IRj",
	"gBY1023Xw2cDciE/2A3K7TPfQ2ANLkDhqrPijYWPgl1wwME1xZSF1ZvAV+D58QAAY3DANVGz0mCxmB9T",
	"YCMzpPAKYyZ3AHTek8mNgql3Mrm/iRqGxsvfu7H9JM39MuvsL/CzrfOJHRRIC3S4L+S90e/Rhth+o3rS",
	"gBxOmAW2YV0j/fAmmWuTIQUjFKPwEivSijcJrxRWEEAMMLqUnOwZyJH36UMGE7hskodzkDmWlSZB3FYi",
	"T2/gRFsN3pLmxzGM1b/clIL+ILY/1LEpJaH8sz9OY7vjR13B3nyHgnUbueEHdkMSrE8uGa7gPJtI4YUa",
	"UeEcnxsZz6ES0vRgCM9vaO+R29UdmlIqFvU7iMcDC8WAnF1Z2LhUfN1kbKuiGjF0w37TDab+QSTQp3Rq",
	"xzm+eiiy17ydfGwnrG4/1dQJsFItis7MBXxrqAN96JoyrhkWWjGKFXr7Gmu49tWo6ePTx9MvMmOfYsX+",
	"mEaMYrtPNWKfLUTp3pe7+b8gcSQsnYhxBwIX8vbCFX9h8bNbjRGrpbYI066eMfVxJhnSdYNEV8K6lD4p",
	"hCy5k6YSGU7gybDbggNNkkE0A9g9AHGlvmHhXGIJYj7HzFlomh829JWbIDrorsO9iBrVdntEujuGQjzo",
	"K7lPaxtvYImYW36R/QndR/7bQGCeiI1emYF8+6EgH8S1hctxSfu7n0pgNIzTIPi3Bg7qQ7Y9nfLVxj7M",
	"JFSeglZgax5UTLl62oPRY3XWxukHZKvFo/dB6n6fmaVIvWt6sRPg2Q7uzx1tW4SDrbbFQ0bGOvSvAWr6",
	"SFgkIGCe3k+WNWjV/NbZVW92K6IBTJq/Zcy/ZWbVK/MnZ6/f9hXiyQef6venP0NmMCiZ9FWkdssNDdG1",
	"G1eRxreP9F9tVkFm3C7CZSrpbL8OPZ3APyhwnfaaTc+ALnW6O0dqxFK2CQaQZqLIfeQRKZO0iRQTdWAP",
	"GbttymEKP7S6ExVvYsi9yXevD/d2exQ9Gpr4r3gSuvp84xuLG/otdG1nH8mPT4o2jF+4tcO4OC1RFG75",
	"z1EY01PT1bQp71BoyerpGXa+cvrd6em0S3J4xOWYZ1xmOl/DVL+fwmopCwwCqHk+nFExQ56aC7i5Rl8K",
	"dbrO/EJNJ00URP2Rid/vaomOEyZpeOldl5B+/0Yl0d8c2O5MkhnjXKZWqmmNGlP1Zw23uJWhdwNX3GcQ",
	"7sC3X0XZ3w9F2oJzG5JfN0hddCS8X7JWxTrSwiOVH+kmJk/gZTPh7YvZdxjt3rqQ5/gbA9rXY00YX0P9",
	"nqIb7/LoXe5zDKF6FD6+6oOjHvHbailQ0UY/usCg98XaN+hPe4140/6Md3j+TtEfDidw1a7WNsBzi00X",
	"pXin5O89x0LOuFxXkGugJMGh744gWRSugaI3bBEFYWcwffnTlReVgFJzo0r7MMDQY4hwkKH7AoO79srf",
	"Hw5M0hsw4KHcfquIZRN33dfTFCRzU/a9UTtpO4HjQcpAEXwgH4aL4XvMRG2bp6HnjNOCVnzTQcMr6YKt",
	"q6pYw3Qw1zvdNcUcIo5eZYV/ZEWaso1OVst1RwUFR3Rs3ybUn5YRoUijFUxfXlz/8CNJ+tRnDKoZH79D",
	"sf1JN4IdklNuxNeujaIOfEzH6Y60Xd1otMLyfP0kNFPfS1F7e8z///VqK33+gvJ01+84pohtr3xEBduB",
	"wr3Rhe9Pi4xmDfsI20EtFNkyMqM1bSZwpl5Su49B5oce4xHOj/+QAqy6maQ1yzrp2NPncDBtpo7gKtNV",
	"N0Psdzq/a3Nef8AILlWbrTQRTmhniSPoYV7zvpHzzbHQEQluz+Qv9StYeYayh5cfFbLNMb0RYesGLO5g",
	"8JsGnmDxuwN6O04R6rgl7+M8EXSnZ+hVN9wh23n0CfzUQj8b6ZJmaRxY32B5GVgUtF2BXaEnwC66dlyR",
	"6RtnxwP8TetSrXLfTd1rq3TkY9n78FQ3zA3aJRz0ehv6xR8ruZeKf9+IsnZa3Y8VNVQEr0aveCJ2OIX2",
	"Zy/uzysMf5vkTm4hCvH3BCX/jeKhO5hh2zA0rhpdHfpTEr0hUL1zfK9vkpv+dYZjDGZ6oeQ/PbwzMuXX",
	"wJpN2+zemT2GLQ0R0ahpwIXGTOnvrQ45xuWvaljHhGW8ZBiTmruW90ZLelvVumBqu9aFQi/IiPloOEcy",
	"0W8SYHLRcNu9073BIl27KVnRYh3rhd8wnpmYFXgOQkGt3qveK/xbeFwFWykPMgilQ4kmdLn2y4mDiNvg",
	"DYqigSz5p4tQZTiBy7bO2AOcfPGGfyVOWmfHKpCtlH7j4uPXKiXutk9xWfvUmuJmmfCm+x2YvZYtYGah",
	"uvLARkf82hkbP43SPA7Hi/6GDAWe/Z+Rmaa+jb8R966KV279OM3hBF7Ws0Jm56D05rxPfwx2C+1qZgHv",
	"0aBtzlFGbFl4BaTyQ6jNdOIYJtkfJSBWt7wc8jsKVg6X3RxbfP32lnbiu/WitFEifnkJ/tZ6QxDn0QmI",
	"1NfESFYYdgww9WGSJrUpkrPkhDs0A4VbP5TDb7fjFRRuNh6x+03acKrb9OP4j5s2PNoa9+qWYSx9e5Hr",
	"u02Ddes8xxgp0TExOBBtsf2wR0k36RAtzofvb9qpmF4L0siKXJm9fXv7vwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
